name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync --all-extras --dev
      - name: Lint
        run: |
          uv run ruff check .
          uv run ruff format --check .
      - name: Type-check
        run: uv run mypy
      - name: Test
        run: uv run pytest
      - name: Generate coverage XML
        if: matrix.python-version == '3.11'
        run: uv run coverage xml
      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: coverage.xml
          flags: python-${{ matrix.python-version }}
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}